# Generated by Django 4.1.3 on 2022-11-10 18:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('email', models.CharField(max_length=90)),
                ('bio', models.TextField(blank=True, max_length=201)),
                ('password', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
